name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Image 1
      uses: docker/build-push-action@v2
      with:
        context: path/to/first-dockerfile-directory
        push: true
        tags: your-dockerhub-username/image1:latest

    - name: Build and push Image 2
      uses: docker/build-push-action@v2
      with:
        context: path/to/second-dockerfile-directory
        push: true
        tags: your-dockerhub-username/image2:latest

    - name: Docker Compose up
      run: docker-compose up -d
